// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ProbeReadinessOKCode is the HTTP code returned for type ProbeReadinessOK
const ProbeReadinessOKCode int = 200

/*ProbeReadinessOK returns a readiness state of the simulator

swagger:response probeReadinessOK
*/
type ProbeReadinessOK struct {

	/*contains the actual readiness state as plain text
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewProbeReadinessOK creates ProbeReadinessOK with default headers values
func NewProbeReadinessOK() *ProbeReadinessOK {

	return &ProbeReadinessOK{}
}

// WithPayload adds the payload to the probe readiness o k response
func (o *ProbeReadinessOK) WithPayload(payload string) *ProbeReadinessOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the probe readiness o k response
func (o *ProbeReadinessOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProbeReadinessOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
