// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ProbeLivenessOKCode is the HTTP code returned for type ProbeLivenessOK
const ProbeLivenessOKCode int = 200

/*
ProbeLivenessOK returns a liveness state of the simulator

swagger:response probeLivenessOK
*/
type ProbeLivenessOK struct {

	/*contains the actual liveness state as plain text
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewProbeLivenessOK creates ProbeLivenessOK with default headers values
func NewProbeLivenessOK() *ProbeLivenessOK {

	return &ProbeLivenessOK{}
}

// WithPayload adds the payload to the probe liveness o k response
func (o *ProbeLivenessOK) WithPayload(payload string) *ProbeLivenessOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the probe liveness o k response
func (o *ProbeLivenessOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProbeLivenessOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
