// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kubedge.proto

package kubedge

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the protocol name.
type EnodeRequest struct {
	Protocol             string   `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnodeRequest) Reset()         { *m = EnodeRequest{} }
func (m *EnodeRequest) String() string { return proto.CompactTextString(m) }
func (*EnodeRequest) ProtoMessage()    {}
func (*EnodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{0}
}

func (m *EnodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnodeRequest.Unmarshal(m, b)
}
func (m *EnodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnodeRequest.Marshal(b, m, deterministic)
}
func (m *EnodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnodeRequest.Merge(m, src)
}
func (m *EnodeRequest) XXX_Size() int {
	return xxx_messageInfo_EnodeRequest.Size(m)
}
func (m *EnodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnodeRequest proto.InternalMessageInfo

func (m *EnodeRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

// The response message containing the protocol or network
type EPCReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EPCReply) Reset()         { *m = EPCReply{} }
func (m *EPCReply) String() string { return proto.CompactTextString(m) }
func (*EPCReply) ProtoMessage()    {}
func (*EPCReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{1}
}

func (m *EPCReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EPCReply.Unmarshal(m, b)
}
func (m *EPCReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EPCReply.Marshal(b, m, deterministic)
}
func (m *EPCReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EPCReply.Merge(m, src)
}
func (m *EPCReply) XXX_Size() int {
	return xxx_messageInfo_EPCReply.Size(m)
}
func (m *EPCReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EPCReply.DiscardUnknown(m)
}

var xxx_messageInfo_EPCReply proto.InternalMessageInfo

func (m *EPCReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// This is for request from UE ( bluetooth/wifi )
type UERequest struct {
	Network              string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UERequest) Reset()         { *m = UERequest{} }
func (m *UERequest) String() string { return proto.CompactTextString(m) }
func (*UERequest) ProtoMessage()    {}
func (*UERequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{2}
}

func (m *UERequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UERequest.Unmarshal(m, b)
}
func (m *UERequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UERequest.Marshal(b, m, deterministic)
}
func (m *UERequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UERequest.Merge(m, src)
}
func (m *UERequest) XXX_Size() int {
	return xxx_messageInfo_UERequest.Size(m)
}
func (m *UERequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UERequest.DiscardUnknown(m)
}

var xxx_messageInfo_UERequest proto.InternalMessageInfo

func (m *UERequest) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

type SIMReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SIMReply) Reset()         { *m = SIMReply{} }
func (m *SIMReply) String() string { return proto.CompactTextString(m) }
func (*SIMReply) ProtoMessage()    {}
func (*SIMReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{3}
}

func (m *SIMReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SIMReply.Unmarshal(m, b)
}
func (m *SIMReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SIMReply.Marshal(b, m, deterministic)
}
func (m *SIMReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SIMReply.Merge(m, src)
}
func (m *SIMReply) XXX_Size() int {
	return xxx_messageInfo_SIMReply.Size(m)
}
func (m *SIMReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SIMReply.DiscardUnknown(m)
}

var xxx_messageInfo_SIMReply proto.InternalMessageInfo

func (m *SIMReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MME_PDN_CONNECT_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MME_PDN_CONNECT_MSG) Reset()         { *m = MME_PDN_CONNECT_MSG{} }
func (m *MME_PDN_CONNECT_MSG) String() string { return proto.CompactTextString(m) }
func (*MME_PDN_CONNECT_MSG) ProtoMessage()    {}
func (*MME_PDN_CONNECT_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{4}
}

func (m *MME_PDN_CONNECT_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MME_PDN_CONNECT_MSG.Unmarshal(m, b)
}
func (m *MME_PDN_CONNECT_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MME_PDN_CONNECT_MSG.Marshal(b, m, deterministic)
}
func (m *MME_PDN_CONNECT_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MME_PDN_CONNECT_MSG.Merge(m, src)
}
func (m *MME_PDN_CONNECT_MSG) XXX_Size() int {
	return xxx_messageInfo_MME_PDN_CONNECT_MSG.Size(m)
}
func (m *MME_PDN_CONNECT_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_MME_PDN_CONNECT_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_MME_PDN_CONNECT_MSG proto.InternalMessageInfo

func (m *MME_PDN_CONNECT_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type MME_PDN_DISCONNECT_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MME_PDN_DISCONNECT_MSG) Reset()         { *m = MME_PDN_DISCONNECT_MSG{} }
func (m *MME_PDN_DISCONNECT_MSG) String() string { return proto.CompactTextString(m) }
func (*MME_PDN_DISCONNECT_MSG) ProtoMessage()    {}
func (*MME_PDN_DISCONNECT_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{5}
}

func (m *MME_PDN_DISCONNECT_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MME_PDN_DISCONNECT_MSG.Unmarshal(m, b)
}
func (m *MME_PDN_DISCONNECT_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MME_PDN_DISCONNECT_MSG.Marshal(b, m, deterministic)
}
func (m *MME_PDN_DISCONNECT_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MME_PDN_DISCONNECT_MSG.Merge(m, src)
}
func (m *MME_PDN_DISCONNECT_MSG) XXX_Size() int {
	return xxx_messageInfo_MME_PDN_DISCONNECT_MSG.Size(m)
}
func (m *MME_PDN_DISCONNECT_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_MME_PDN_DISCONNECT_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_MME_PDN_DISCONNECT_MSG proto.InternalMessageInfo

func (m *MME_PDN_DISCONNECT_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type MME_ATTACH_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MME_ATTACH_MSG) Reset()         { *m = MME_ATTACH_MSG{} }
func (m *MME_ATTACH_MSG) String() string { return proto.CompactTextString(m) }
func (*MME_ATTACH_MSG) ProtoMessage()    {}
func (*MME_ATTACH_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{6}
}

func (m *MME_ATTACH_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MME_ATTACH_MSG.Unmarshal(m, b)
}
func (m *MME_ATTACH_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MME_ATTACH_MSG.Marshal(b, m, deterministic)
}
func (m *MME_ATTACH_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MME_ATTACH_MSG.Merge(m, src)
}
func (m *MME_ATTACH_MSG) XXX_Size() int {
	return xxx_messageInfo_MME_ATTACH_MSG.Size(m)
}
func (m *MME_ATTACH_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_MME_ATTACH_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_MME_ATTACH_MSG proto.InternalMessageInfo

func (m *MME_ATTACH_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type MME_DETACH_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MME_DETACH_MSG) Reset()         { *m = MME_DETACH_MSG{} }
func (m *MME_DETACH_MSG) String() string { return proto.CompactTextString(m) }
func (*MME_DETACH_MSG) ProtoMessage()    {}
func (*MME_DETACH_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{7}
}

func (m *MME_DETACH_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MME_DETACH_MSG.Unmarshal(m, b)
}
func (m *MME_DETACH_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MME_DETACH_MSG.Marshal(b, m, deterministic)
}
func (m *MME_DETACH_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MME_DETACH_MSG.Merge(m, src)
}
func (m *MME_DETACH_MSG) XXX_Size() int {
	return xxx_messageInfo_MME_DETACH_MSG.Size(m)
}
func (m *MME_DETACH_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_MME_DETACH_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_MME_DETACH_MSG proto.InternalMessageInfo

func (m *MME_DETACH_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type MME_HO_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MME_HO_MSG) Reset()         { *m = MME_HO_MSG{} }
func (m *MME_HO_MSG) String() string { return proto.CompactTextString(m) }
func (*MME_HO_MSG) ProtoMessage()    {}
func (*MME_HO_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{8}
}

func (m *MME_HO_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MME_HO_MSG.Unmarshal(m, b)
}
func (m *MME_HO_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MME_HO_MSG.Marshal(b, m, deterministic)
}
func (m *MME_HO_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MME_HO_MSG.Merge(m, src)
}
func (m *MME_HO_MSG) XXX_Size() int {
	return xxx_messageInfo_MME_HO_MSG.Size(m)
}
func (m *MME_HO_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_MME_HO_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_MME_HO_MSG proto.InternalMessageInfo

func (m *MME_HO_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type MME_TAU_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MME_TAU_MSG) Reset()         { *m = MME_TAU_MSG{} }
func (m *MME_TAU_MSG) String() string { return proto.CompactTextString(m) }
func (*MME_TAU_MSG) ProtoMessage()    {}
func (*MME_TAU_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{9}
}

func (m *MME_TAU_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MME_TAU_MSG.Unmarshal(m, b)
}
func (m *MME_TAU_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MME_TAU_MSG.Marshal(b, m, deterministic)
}
func (m *MME_TAU_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MME_TAU_MSG.Merge(m, src)
}
func (m *MME_TAU_MSG) XXX_Size() int {
	return xxx_messageInfo_MME_TAU_MSG.Size(m)
}
func (m *MME_TAU_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_MME_TAU_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_MME_TAU_MSG proto.InternalMessageInfo

func (m *MME_TAU_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type MME_SERVICE_REQUEST_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MME_SERVICE_REQUEST_MSG) Reset()         { *m = MME_SERVICE_REQUEST_MSG{} }
func (m *MME_SERVICE_REQUEST_MSG) String() string { return proto.CompactTextString(m) }
func (*MME_SERVICE_REQUEST_MSG) ProtoMessage()    {}
func (*MME_SERVICE_REQUEST_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{10}
}

func (m *MME_SERVICE_REQUEST_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MME_SERVICE_REQUEST_MSG.Unmarshal(m, b)
}
func (m *MME_SERVICE_REQUEST_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MME_SERVICE_REQUEST_MSG.Marshal(b, m, deterministic)
}
func (m *MME_SERVICE_REQUEST_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MME_SERVICE_REQUEST_MSG.Merge(m, src)
}
func (m *MME_SERVICE_REQUEST_MSG) XXX_Size() int {
	return xxx_messageInfo_MME_SERVICE_REQUEST_MSG.Size(m)
}
func (m *MME_SERVICE_REQUEST_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_MME_SERVICE_REQUEST_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_MME_SERVICE_REQUEST_MSG proto.InternalMessageInfo

func (m *MME_SERVICE_REQUEST_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type SGW_SESSION_CREATION_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SGW_SESSION_CREATION_MSG) Reset()         { *m = SGW_SESSION_CREATION_MSG{} }
func (m *SGW_SESSION_CREATION_MSG) String() string { return proto.CompactTextString(m) }
func (*SGW_SESSION_CREATION_MSG) ProtoMessage()    {}
func (*SGW_SESSION_CREATION_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{11}
}

func (m *SGW_SESSION_CREATION_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SGW_SESSION_CREATION_MSG.Unmarshal(m, b)
}
func (m *SGW_SESSION_CREATION_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SGW_SESSION_CREATION_MSG.Marshal(b, m, deterministic)
}
func (m *SGW_SESSION_CREATION_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SGW_SESSION_CREATION_MSG.Merge(m, src)
}
func (m *SGW_SESSION_CREATION_MSG) XXX_Size() int {
	return xxx_messageInfo_SGW_SESSION_CREATION_MSG.Size(m)
}
func (m *SGW_SESSION_CREATION_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_SGW_SESSION_CREATION_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_SGW_SESSION_CREATION_MSG proto.InternalMessageInfo

func (m *SGW_SESSION_CREATION_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type SGW_SESSION_DELETION_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SGW_SESSION_DELETION_MSG) Reset()         { *m = SGW_SESSION_DELETION_MSG{} }
func (m *SGW_SESSION_DELETION_MSG) String() string { return proto.CompactTextString(m) }
func (*SGW_SESSION_DELETION_MSG) ProtoMessage()    {}
func (*SGW_SESSION_DELETION_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{12}
}

func (m *SGW_SESSION_DELETION_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SGW_SESSION_DELETION_MSG.Unmarshal(m, b)
}
func (m *SGW_SESSION_DELETION_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SGW_SESSION_DELETION_MSG.Marshal(b, m, deterministic)
}
func (m *SGW_SESSION_DELETION_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SGW_SESSION_DELETION_MSG.Merge(m, src)
}
func (m *SGW_SESSION_DELETION_MSG) XXX_Size() int {
	return xxx_messageInfo_SGW_SESSION_DELETION_MSG.Size(m)
}
func (m *SGW_SESSION_DELETION_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_SGW_SESSION_DELETION_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_SGW_SESSION_DELETION_MSG proto.InternalMessageInfo

func (m *SGW_SESSION_DELETION_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type SGW_BEARER_CREATION_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SGW_BEARER_CREATION_MSG) Reset()         { *m = SGW_BEARER_CREATION_MSG{} }
func (m *SGW_BEARER_CREATION_MSG) String() string { return proto.CompactTextString(m) }
func (*SGW_BEARER_CREATION_MSG) ProtoMessage()    {}
func (*SGW_BEARER_CREATION_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{13}
}

func (m *SGW_BEARER_CREATION_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SGW_BEARER_CREATION_MSG.Unmarshal(m, b)
}
func (m *SGW_BEARER_CREATION_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SGW_BEARER_CREATION_MSG.Marshal(b, m, deterministic)
}
func (m *SGW_BEARER_CREATION_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SGW_BEARER_CREATION_MSG.Merge(m, src)
}
func (m *SGW_BEARER_CREATION_MSG) XXX_Size() int {
	return xxx_messageInfo_SGW_BEARER_CREATION_MSG.Size(m)
}
func (m *SGW_BEARER_CREATION_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_SGW_BEARER_CREATION_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_SGW_BEARER_CREATION_MSG proto.InternalMessageInfo

func (m *SGW_BEARER_CREATION_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type SGW_BEARER_DELETION_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SGW_BEARER_DELETION_MSG) Reset()         { *m = SGW_BEARER_DELETION_MSG{} }
func (m *SGW_BEARER_DELETION_MSG) String() string { return proto.CompactTextString(m) }
func (*SGW_BEARER_DELETION_MSG) ProtoMessage()    {}
func (*SGW_BEARER_DELETION_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{14}
}

func (m *SGW_BEARER_DELETION_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SGW_BEARER_DELETION_MSG.Unmarshal(m, b)
}
func (m *SGW_BEARER_DELETION_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SGW_BEARER_DELETION_MSG.Marshal(b, m, deterministic)
}
func (m *SGW_BEARER_DELETION_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SGW_BEARER_DELETION_MSG.Merge(m, src)
}
func (m *SGW_BEARER_DELETION_MSG) XXX_Size() int {
	return xxx_messageInfo_SGW_BEARER_DELETION_MSG.Size(m)
}
func (m *SGW_BEARER_DELETION_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_SGW_BEARER_DELETION_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_SGW_BEARER_DELETION_MSG proto.InternalMessageInfo

func (m *SGW_BEARER_DELETION_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type SGW_BEARER_MODIFICATION_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SGW_BEARER_MODIFICATION_MSG) Reset()         { *m = SGW_BEARER_MODIFICATION_MSG{} }
func (m *SGW_BEARER_MODIFICATION_MSG) String() string { return proto.CompactTextString(m) }
func (*SGW_BEARER_MODIFICATION_MSG) ProtoMessage()    {}
func (*SGW_BEARER_MODIFICATION_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{15}
}

func (m *SGW_BEARER_MODIFICATION_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SGW_BEARER_MODIFICATION_MSG.Unmarshal(m, b)
}
func (m *SGW_BEARER_MODIFICATION_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SGW_BEARER_MODIFICATION_MSG.Marshal(b, m, deterministic)
}
func (m *SGW_BEARER_MODIFICATION_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SGW_BEARER_MODIFICATION_MSG.Merge(m, src)
}
func (m *SGW_BEARER_MODIFICATION_MSG) XXX_Size() int {
	return xxx_messageInfo_SGW_BEARER_MODIFICATION_MSG.Size(m)
}
func (m *SGW_BEARER_MODIFICATION_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_SGW_BEARER_MODIFICATION_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_SGW_BEARER_MODIFICATION_MSG proto.InternalMessageInfo

func (m *SGW_BEARER_MODIFICATION_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type SGW_DEDICATED_BEARER_ACTIVATE_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SGW_DEDICATED_BEARER_ACTIVATE_MSG) Reset()         { *m = SGW_DEDICATED_BEARER_ACTIVATE_MSG{} }
func (m *SGW_DEDICATED_BEARER_ACTIVATE_MSG) String() string { return proto.CompactTextString(m) }
func (*SGW_DEDICATED_BEARER_ACTIVATE_MSG) ProtoMessage()    {}
func (*SGW_DEDICATED_BEARER_ACTIVATE_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{16}
}

func (m *SGW_DEDICATED_BEARER_ACTIVATE_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SGW_DEDICATED_BEARER_ACTIVATE_MSG.Unmarshal(m, b)
}
func (m *SGW_DEDICATED_BEARER_ACTIVATE_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SGW_DEDICATED_BEARER_ACTIVATE_MSG.Marshal(b, m, deterministic)
}
func (m *SGW_DEDICATED_BEARER_ACTIVATE_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SGW_DEDICATED_BEARER_ACTIVATE_MSG.Merge(m, src)
}
func (m *SGW_DEDICATED_BEARER_ACTIVATE_MSG) XXX_Size() int {
	return xxx_messageInfo_SGW_DEDICATED_BEARER_ACTIVATE_MSG.Size(m)
}
func (m *SGW_DEDICATED_BEARER_ACTIVATE_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_SGW_DEDICATED_BEARER_ACTIVATE_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_SGW_DEDICATED_BEARER_ACTIVATE_MSG proto.InternalMessageInfo

func (m *SGW_DEDICATED_BEARER_ACTIVATE_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type SGW_DEDICATED_BEARER_DEACTIVATE_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SGW_DEDICATED_BEARER_DEACTIVATE_MSG) Reset()         { *m = SGW_DEDICATED_BEARER_DEACTIVATE_MSG{} }
func (m *SGW_DEDICATED_BEARER_DEACTIVATE_MSG) String() string { return proto.CompactTextString(m) }
func (*SGW_DEDICATED_BEARER_DEACTIVATE_MSG) ProtoMessage()    {}
func (*SGW_DEDICATED_BEARER_DEACTIVATE_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{17}
}

func (m *SGW_DEDICATED_BEARER_DEACTIVATE_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SGW_DEDICATED_BEARER_DEACTIVATE_MSG.Unmarshal(m, b)
}
func (m *SGW_DEDICATED_BEARER_DEACTIVATE_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SGW_DEDICATED_BEARER_DEACTIVATE_MSG.Marshal(b, m, deterministic)
}
func (m *SGW_DEDICATED_BEARER_DEACTIVATE_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SGW_DEDICATED_BEARER_DEACTIVATE_MSG.Merge(m, src)
}
func (m *SGW_DEDICATED_BEARER_DEACTIVATE_MSG) XXX_Size() int {
	return xxx_messageInfo_SGW_DEDICATED_BEARER_DEACTIVATE_MSG.Size(m)
}
func (m *SGW_DEDICATED_BEARER_DEACTIVATE_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_SGW_DEDICATED_BEARER_DEACTIVATE_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_SGW_DEDICATED_BEARER_DEACTIVATE_MSG proto.InternalMessageInfo

func (m *SGW_DEDICATED_BEARER_DEACTIVATE_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type ENB_RRC_CONN_SETUP_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ENB_RRC_CONN_SETUP_MSG) Reset()         { *m = ENB_RRC_CONN_SETUP_MSG{} }
func (m *ENB_RRC_CONN_SETUP_MSG) String() string { return proto.CompactTextString(m) }
func (*ENB_RRC_CONN_SETUP_MSG) ProtoMessage()    {}
func (*ENB_RRC_CONN_SETUP_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{18}
}

func (m *ENB_RRC_CONN_SETUP_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ENB_RRC_CONN_SETUP_MSG.Unmarshal(m, b)
}
func (m *ENB_RRC_CONN_SETUP_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ENB_RRC_CONN_SETUP_MSG.Marshal(b, m, deterministic)
}
func (m *ENB_RRC_CONN_SETUP_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ENB_RRC_CONN_SETUP_MSG.Merge(m, src)
}
func (m *ENB_RRC_CONN_SETUP_MSG) XXX_Size() int {
	return xxx_messageInfo_ENB_RRC_CONN_SETUP_MSG.Size(m)
}
func (m *ENB_RRC_CONN_SETUP_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_ENB_RRC_CONN_SETUP_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_ENB_RRC_CONN_SETUP_MSG proto.InternalMessageInfo

func (m *ENB_RRC_CONN_SETUP_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type ENB_S1_SIG_CONN_SETUP_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ENB_S1_SIG_CONN_SETUP_MSG) Reset()         { *m = ENB_S1_SIG_CONN_SETUP_MSG{} }
func (m *ENB_S1_SIG_CONN_SETUP_MSG) String() string { return proto.CompactTextString(m) }
func (*ENB_S1_SIG_CONN_SETUP_MSG) ProtoMessage()    {}
func (*ENB_S1_SIG_CONN_SETUP_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{19}
}

func (m *ENB_S1_SIG_CONN_SETUP_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ENB_S1_SIG_CONN_SETUP_MSG.Unmarshal(m, b)
}
func (m *ENB_S1_SIG_CONN_SETUP_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ENB_S1_SIG_CONN_SETUP_MSG.Marshal(b, m, deterministic)
}
func (m *ENB_S1_SIG_CONN_SETUP_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ENB_S1_SIG_CONN_SETUP_MSG.Merge(m, src)
}
func (m *ENB_S1_SIG_CONN_SETUP_MSG) XXX_Size() int {
	return xxx_messageInfo_ENB_S1_SIG_CONN_SETUP_MSG.Size(m)
}
func (m *ENB_S1_SIG_CONN_SETUP_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_ENB_S1_SIG_CONN_SETUP_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_ENB_S1_SIG_CONN_SETUP_MSG proto.InternalMessageInfo

func (m *ENB_S1_SIG_CONN_SETUP_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type ENB_INITIAL_CTXT_SETUP_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ENB_INITIAL_CTXT_SETUP_MSG) Reset()         { *m = ENB_INITIAL_CTXT_SETUP_MSG{} }
func (m *ENB_INITIAL_CTXT_SETUP_MSG) String() string { return proto.CompactTextString(m) }
func (*ENB_INITIAL_CTXT_SETUP_MSG) ProtoMessage()    {}
func (*ENB_INITIAL_CTXT_SETUP_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{20}
}

func (m *ENB_INITIAL_CTXT_SETUP_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ENB_INITIAL_CTXT_SETUP_MSG.Unmarshal(m, b)
}
func (m *ENB_INITIAL_CTXT_SETUP_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ENB_INITIAL_CTXT_SETUP_MSG.Marshal(b, m, deterministic)
}
func (m *ENB_INITIAL_CTXT_SETUP_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ENB_INITIAL_CTXT_SETUP_MSG.Merge(m, src)
}
func (m *ENB_INITIAL_CTXT_SETUP_MSG) XXX_Size() int {
	return xxx_messageInfo_ENB_INITIAL_CTXT_SETUP_MSG.Size(m)
}
func (m *ENB_INITIAL_CTXT_SETUP_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_ENB_INITIAL_CTXT_SETUP_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_ENB_INITIAL_CTXT_SETUP_MSG proto.InternalMessageInfo

func (m *ENB_INITIAL_CTXT_SETUP_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type ENB_UE_CTX_RELEASE_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ENB_UE_CTX_RELEASE_MSG) Reset()         { *m = ENB_UE_CTX_RELEASE_MSG{} }
func (m *ENB_UE_CTX_RELEASE_MSG) String() string { return proto.CompactTextString(m) }
func (*ENB_UE_CTX_RELEASE_MSG) ProtoMessage()    {}
func (*ENB_UE_CTX_RELEASE_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{21}
}

func (m *ENB_UE_CTX_RELEASE_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ENB_UE_CTX_RELEASE_MSG.Unmarshal(m, b)
}
func (m *ENB_UE_CTX_RELEASE_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ENB_UE_CTX_RELEASE_MSG.Marshal(b, m, deterministic)
}
func (m *ENB_UE_CTX_RELEASE_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ENB_UE_CTX_RELEASE_MSG.Merge(m, src)
}
func (m *ENB_UE_CTX_RELEASE_MSG) XXX_Size() int {
	return xxx_messageInfo_ENB_UE_CTX_RELEASE_MSG.Size(m)
}
func (m *ENB_UE_CTX_RELEASE_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_ENB_UE_CTX_RELEASE_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_ENB_UE_CTX_RELEASE_MSG proto.InternalMessageInfo

func (m *ENB_UE_CTX_RELEASE_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type ENB_X2HO_PREP_OUT_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ENB_X2HO_PREP_OUT_MSG) Reset()         { *m = ENB_X2HO_PREP_OUT_MSG{} }
func (m *ENB_X2HO_PREP_OUT_MSG) String() string { return proto.CompactTextString(m) }
func (*ENB_X2HO_PREP_OUT_MSG) ProtoMessage()    {}
func (*ENB_X2HO_PREP_OUT_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{22}
}

func (m *ENB_X2HO_PREP_OUT_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ENB_X2HO_PREP_OUT_MSG.Unmarshal(m, b)
}
func (m *ENB_X2HO_PREP_OUT_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ENB_X2HO_PREP_OUT_MSG.Marshal(b, m, deterministic)
}
func (m *ENB_X2HO_PREP_OUT_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ENB_X2HO_PREP_OUT_MSG.Merge(m, src)
}
func (m *ENB_X2HO_PREP_OUT_MSG) XXX_Size() int {
	return xxx_messageInfo_ENB_X2HO_PREP_OUT_MSG.Size(m)
}
func (m *ENB_X2HO_PREP_OUT_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_ENB_X2HO_PREP_OUT_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_ENB_X2HO_PREP_OUT_MSG proto.InternalMessageInfo

func (m *ENB_X2HO_PREP_OUT_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type ENB_X2HO_PREP_IN_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ENB_X2HO_PREP_IN_MSG) Reset()         { *m = ENB_X2HO_PREP_IN_MSG{} }
func (m *ENB_X2HO_PREP_IN_MSG) String() string { return proto.CompactTextString(m) }
func (*ENB_X2HO_PREP_IN_MSG) ProtoMessage()    {}
func (*ENB_X2HO_PREP_IN_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{23}
}

func (m *ENB_X2HO_PREP_IN_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ENB_X2HO_PREP_IN_MSG.Unmarshal(m, b)
}
func (m *ENB_X2HO_PREP_IN_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ENB_X2HO_PREP_IN_MSG.Marshal(b, m, deterministic)
}
func (m *ENB_X2HO_PREP_IN_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ENB_X2HO_PREP_IN_MSG.Merge(m, src)
}
func (m *ENB_X2HO_PREP_IN_MSG) XXX_Size() int {
	return xxx_messageInfo_ENB_X2HO_PREP_IN_MSG.Size(m)
}
func (m *ENB_X2HO_PREP_IN_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_ENB_X2HO_PREP_IN_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_ENB_X2HO_PREP_IN_MSG proto.InternalMessageInfo

func (m *ENB_X2HO_PREP_IN_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type ENB_X2HO_EXEC_OUT_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ENB_X2HO_EXEC_OUT_MSG) Reset()         { *m = ENB_X2HO_EXEC_OUT_MSG{} }
func (m *ENB_X2HO_EXEC_OUT_MSG) String() string { return proto.CompactTextString(m) }
func (*ENB_X2HO_EXEC_OUT_MSG) ProtoMessage()    {}
func (*ENB_X2HO_EXEC_OUT_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{24}
}

func (m *ENB_X2HO_EXEC_OUT_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ENB_X2HO_EXEC_OUT_MSG.Unmarshal(m, b)
}
func (m *ENB_X2HO_EXEC_OUT_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ENB_X2HO_EXEC_OUT_MSG.Marshal(b, m, deterministic)
}
func (m *ENB_X2HO_EXEC_OUT_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ENB_X2HO_EXEC_OUT_MSG.Merge(m, src)
}
func (m *ENB_X2HO_EXEC_OUT_MSG) XXX_Size() int {
	return xxx_messageInfo_ENB_X2HO_EXEC_OUT_MSG.Size(m)
}
func (m *ENB_X2HO_EXEC_OUT_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_ENB_X2HO_EXEC_OUT_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_ENB_X2HO_EXEC_OUT_MSG proto.InternalMessageInfo

func (m *ENB_X2HO_EXEC_OUT_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type ENB_X2HO_EXEC_IN_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ENB_X2HO_EXEC_IN_MSG) Reset()         { *m = ENB_X2HO_EXEC_IN_MSG{} }
func (m *ENB_X2HO_EXEC_IN_MSG) String() string { return proto.CompactTextString(m) }
func (*ENB_X2HO_EXEC_IN_MSG) ProtoMessage()    {}
func (*ENB_X2HO_EXEC_IN_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{25}
}

func (m *ENB_X2HO_EXEC_IN_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ENB_X2HO_EXEC_IN_MSG.Unmarshal(m, b)
}
func (m *ENB_X2HO_EXEC_IN_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ENB_X2HO_EXEC_IN_MSG.Marshal(b, m, deterministic)
}
func (m *ENB_X2HO_EXEC_IN_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ENB_X2HO_EXEC_IN_MSG.Merge(m, src)
}
func (m *ENB_X2HO_EXEC_IN_MSG) XXX_Size() int {
	return xxx_messageInfo_ENB_X2HO_EXEC_IN_MSG.Size(m)
}
func (m *ENB_X2HO_EXEC_IN_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_ENB_X2HO_EXEC_IN_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_ENB_X2HO_EXEC_IN_MSG proto.InternalMessageInfo

func (m *ENB_X2HO_EXEC_IN_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type ENB_ERAB_SETUP_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ENB_ERAB_SETUP_MSG) Reset()         { *m = ENB_ERAB_SETUP_MSG{} }
func (m *ENB_ERAB_SETUP_MSG) String() string { return proto.CompactTextString(m) }
func (*ENB_ERAB_SETUP_MSG) ProtoMessage()    {}
func (*ENB_ERAB_SETUP_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{26}
}

func (m *ENB_ERAB_SETUP_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ENB_ERAB_SETUP_MSG.Unmarshal(m, b)
}
func (m *ENB_ERAB_SETUP_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ENB_ERAB_SETUP_MSG.Marshal(b, m, deterministic)
}
func (m *ENB_ERAB_SETUP_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ENB_ERAB_SETUP_MSG.Merge(m, src)
}
func (m *ENB_ERAB_SETUP_MSG) XXX_Size() int {
	return xxx_messageInfo_ENB_ERAB_SETUP_MSG.Size(m)
}
func (m *ENB_ERAB_SETUP_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_ENB_ERAB_SETUP_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_ENB_ERAB_SETUP_MSG proto.InternalMessageInfo

func (m *ENB_ERAB_SETUP_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

type ENB_ERAB_RELEASE_MSG struct {
	Imsi                 string   `protobuf:"bytes,1,opt,name=imsi,proto3" json:"imsi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ENB_ERAB_RELEASE_MSG) Reset()         { *m = ENB_ERAB_RELEASE_MSG{} }
func (m *ENB_ERAB_RELEASE_MSG) String() string { return proto.CompactTextString(m) }
func (*ENB_ERAB_RELEASE_MSG) ProtoMessage()    {}
func (*ENB_ERAB_RELEASE_MSG) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7659456244382b8, []int{27}
}

func (m *ENB_ERAB_RELEASE_MSG) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ENB_ERAB_RELEASE_MSG.Unmarshal(m, b)
}
func (m *ENB_ERAB_RELEASE_MSG) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ENB_ERAB_RELEASE_MSG.Marshal(b, m, deterministic)
}
func (m *ENB_ERAB_RELEASE_MSG) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ENB_ERAB_RELEASE_MSG.Merge(m, src)
}
func (m *ENB_ERAB_RELEASE_MSG) XXX_Size() int {
	return xxx_messageInfo_ENB_ERAB_RELEASE_MSG.Size(m)
}
func (m *ENB_ERAB_RELEASE_MSG) XXX_DiscardUnknown() {
	xxx_messageInfo_ENB_ERAB_RELEASE_MSG.DiscardUnknown(m)
}

var xxx_messageInfo_ENB_ERAB_RELEASE_MSG proto.InternalMessageInfo

func (m *ENB_ERAB_RELEASE_MSG) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

func init() {
	proto.RegisterType((*EnodeRequest)(nil), "kubedge.EnodeRequest")
	proto.RegisterType((*EPCReply)(nil), "kubedge.EPCReply")
	proto.RegisterType((*UERequest)(nil), "kubedge.UERequest")
	proto.RegisterType((*SIMReply)(nil), "kubedge.SIMReply")
	proto.RegisterType((*MME_PDN_CONNECT_MSG)(nil), "kubedge.MME_PDN_CONNECT_MSG")
	proto.RegisterType((*MME_PDN_DISCONNECT_MSG)(nil), "kubedge.MME_PDN_DISCONNECT_MSG")
	proto.RegisterType((*MME_ATTACH_MSG)(nil), "kubedge.MME_ATTACH_MSG")
	proto.RegisterType((*MME_DETACH_MSG)(nil), "kubedge.MME_DETACH_MSG")
	proto.RegisterType((*MME_HO_MSG)(nil), "kubedge.MME_HO_MSG")
	proto.RegisterType((*MME_TAU_MSG)(nil), "kubedge.MME_TAU_MSG")
	proto.RegisterType((*MME_SERVICE_REQUEST_MSG)(nil), "kubedge.MME_SERVICE_REQUEST_MSG")
	proto.RegisterType((*SGW_SESSION_CREATION_MSG)(nil), "kubedge.SGW_SESSION_CREATION_MSG")
	proto.RegisterType((*SGW_SESSION_DELETION_MSG)(nil), "kubedge.SGW_SESSION_DELETION_MSG")
	proto.RegisterType((*SGW_BEARER_CREATION_MSG)(nil), "kubedge.SGW_BEARER_CREATION_MSG")
	proto.RegisterType((*SGW_BEARER_DELETION_MSG)(nil), "kubedge.SGW_BEARER_DELETION_MSG")
	proto.RegisterType((*SGW_BEARER_MODIFICATION_MSG)(nil), "kubedge.SGW_BEARER_MODIFICATION_MSG")
	proto.RegisterType((*SGW_DEDICATED_BEARER_ACTIVATE_MSG)(nil), "kubedge.SGW_DEDICATED_BEARER_ACTIVATE_MSG")
	proto.RegisterType((*SGW_DEDICATED_BEARER_DEACTIVATE_MSG)(nil), "kubedge.SGW_DEDICATED_BEARER_DEACTIVATE_MSG")
	proto.RegisterType((*ENB_RRC_CONN_SETUP_MSG)(nil), "kubedge.ENB_RRC_CONN_SETUP_MSG")
	proto.RegisterType((*ENB_S1_SIG_CONN_SETUP_MSG)(nil), "kubedge.ENB_S1_SIG_CONN_SETUP_MSG")
	proto.RegisterType((*ENB_INITIAL_CTXT_SETUP_MSG)(nil), "kubedge.ENB_INITIAL_CTXT_SETUP_MSG")
	proto.RegisterType((*ENB_UE_CTX_RELEASE_MSG)(nil), "kubedge.ENB_UE_CTX_RELEASE_MSG")
	proto.RegisterType((*ENB_X2HO_PREP_OUT_MSG)(nil), "kubedge.ENB_X2HO_PREP_OUT_MSG")
	proto.RegisterType((*ENB_X2HO_PREP_IN_MSG)(nil), "kubedge.ENB_X2HO_PREP_IN_MSG")
	proto.RegisterType((*ENB_X2HO_EXEC_OUT_MSG)(nil), "kubedge.ENB_X2HO_EXEC_OUT_MSG")
	proto.RegisterType((*ENB_X2HO_EXEC_IN_MSG)(nil), "kubedge.ENB_X2HO_EXEC_IN_MSG")
	proto.RegisterType((*ENB_ERAB_SETUP_MSG)(nil), "kubedge.ENB_ERAB_SETUP_MSG")
	proto.RegisterType((*ENB_ERAB_RELEASE_MSG)(nil), "kubedge.ENB_ERAB_RELEASE_MSG")
}

func init() { proto.RegisterFile("kubedge.proto", fileDescriptor_e7659456244382b8) }

var fileDescriptor_e7659456244382b8 = []byte{
	// 764 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x97, 0xef, 0x4f, 0xd3, 0x5c,
	0x14, 0xc7, 0x21, 0x79, 0xc2, 0xe0, 0x3c, 0x0a, 0x72, 0xf8, 0x35, 0x41, 0x04, 0x0a, 0x26, 0x88,
	0x80, 0x02, 0x26, 0x44, 0xdf, 0x75, 0xed, 0x61, 0xab, 0x6e, 0xdd, 0xbc, 0xed, 0x80, 0x77, 0x55,
	0xa0, 0x21, 0x04, 0xc6, 0x90, 0x0d, 0x8d, 0x2f, 0xfd, 0xcf, 0xcd, 0x5d, 0xdb, 0xad, 0xb7, 0xbd,
	0xb7, 0xed, 0xbb, 0x5d, 0xf2, 0x39, 0x9f, 0x9e, 0xbb, 0xac, 0xdf, 0x6f, 0x80, 0xe7, 0xb7, 0x4f,
	0x17, 0xfe, 0xd5, 0xb5, 0xbf, 0xff, 0xf0, 0xd8, 0xed, 0x77, 0xb1, 0x14, 0x1e, 0xb5, 0x1d, 0x78,
	0x46, 0xf7, 0xdd, 0x2b, 0x9f, 0xf9, 0x3f, 0x9f, 0xfc, 0x5e, 0x1f, 0x97, 0x61, 0x72, 0x40, 0x5c,
	0x76, 0xef, 0xca, 0xe3, 0xeb, 0xe3, 0xdb, 0x53, 0x6c, 0x78, 0xd6, 0xb6, 0x60, 0x92, 0x5a, 0x06,
	0xf3, 0x1f, 0xee, 0xfe, 0x60, 0x19, 0x4a, 0x1d, 0xbf, 0xd7, 0xfb, 0x71, 0xed, 0x87, 0x58, 0x74,
	0xd4, 0xde, 0xc0, 0x54, 0x9b, 0x22, 0x5d, 0x19, 0x4a, 0xf7, 0x7e, 0xff, 0x77, 0xf7, 0xf1, 0x36,
	0xc2, 0xc2, 0x23, 0x97, 0x39, 0x56, 0x23, 0x4f, 0xf6, 0x16, 0xe6, 0x1a, 0x0d, 0xf2, 0x5a, 0xa6,
	0xed, 0x19, 0x4d, 0xdb, 0x26, 0xc3, 0xf5, 0x1a, 0x4e, 0x15, 0x11, 0xfe, 0xbb, 0xe9, 0xf4, 0x6e,
	0x42, 0x7a, 0xf0, 0x59, 0xdb, 0x85, 0xc5, 0x08, 0x35, 0x2d, 0x27, 0x8f, 0xde, 0x82, 0x69, 0x4e,
	0xeb, 0xae, 0xab, 0x1b, 0xb5, 0x3c, 0xca, 0xa4, 0x4c, 0x6a, 0x1d, 0x80, 0x53, 0xb5, 0xa6, 0x92,
	0xd8, 0x80, 0xff, 0x39, 0xe1, 0xea, 0x6d, 0x25, 0xb2, 0x07, 0x4b, 0x1c, 0x71, 0x88, 0x9d, 0x5a,
	0x06, 0x79, 0x8c, 0xbe, 0xb5, 0xc9, 0x51, 0xef, 0xbf, 0x0f, 0x65, 0xa7, 0x7a, 0xe6, 0x39, 0xe4,
	0x38, 0x56, 0xd3, 0xf6, 0x0c, 0x46, 0xba, 0xcb, 0x3f, 0x14, 0xe4, 0x4d, 0xaa, 0x53, 0x26, 0xbf,
	0x07, 0x4b, 0x9c, 0xaf, 0x90, 0xce, 0x88, 0xe5, 0xeb, 0x45, 0x3c, 0xd7, 0x7e, 0x00, 0x2b, 0x31,
	0xbc, 0xd1, 0x34, 0xad, 0x13, 0xcb, 0xc8, 0x7e, 0xc2, 0x31, 0x6c, 0xf0, 0x11, 0x93, 0x4c, 0x4e,
	0x92, 0x19, 0x0d, 0xeb, 0x86, 0x6b, 0x9d, 0xea, 0x2e, 0x29, 0x07, 0x3f, 0xc1, 0xa6, 0x74, 0xd0,
	0xa4, 0xdc, 0xd1, 0x5d, 0x58, 0x24, 0xbb, 0xe2, 0x31, 0x66, 0x0c, 0x7e, 0x7d, 0x9e, 0x43, 0x6e,
	0xbb, 0xa5, 0xa4, 0xdf, 0xc3, 0x4b, 0x4e, 0x3b, 0x07, 0x9e, 0x63, 0x55, 0x8b, 0x0c, 0x7c, 0x80,
	0x65, 0x3e, 0x60, 0xd9, 0x96, 0x6b, 0xe9, 0x75, 0xcf, 0x70, 0xcf, 0xdd, 0x9c, 0x89, 0x70, 0xa1,
	0x36, 0x71, 0xd8, 0x63, 0x54, 0x27, 0xdd, 0x51, 0xaf, 0xff, 0x0e, 0x16, 0x38, 0x7d, 0x7e, 0x58,
	0x6b, 0x7a, 0x2d, 0x46, 0x2d, 0xaf, 0xd9, 0x56, 0xff, 0xa0, 0x76, 0x60, 0x5e, 0x84, 0x2d, 0xbb,
	0x90, 0x98, 0xce, 0xc9, 0x28, 0x2c, 0x1e, 0xc0, 0x19, 0xe2, 0x6d, 0x40, 0xce, 0x12, 0xd3, 0x2b,
	0x39, 0xdf, 0x44, 0x68, 0x1d, 0x90, 0x39, 0xdf, 0xc3, 0xe1, 0xdf, 0x19, 0x28, 0x7d, 0x0d, 0xf2,
	0x0e, 0x8f, 0x61, 0xea, 0xe4, 0xe6, 0x97, 0x5f, 0x35, 0xfd, 0x4e, 0x17, 0x17, 0xf6, 0xa3, 0x54,
	0x8c, 0x67, 0xe0, 0xf2, 0xec, 0xe8, 0xcf, 0x61, 0xdc, 0x69, 0x63, 0x78, 0x04, 0x93, 0xa6, 0xdf,
	0xf7, 0x2f, 0xfb, 0xf6, 0x19, 0xe2, 0x10, 0x18, 0x26, 0x9d, 0x7c, 0xc8, 0x84, 0x99, 0x44, 0x7c,
	0xe1, 0xab, 0x21, 0x27, 0x09, 0xb6, 0x98, 0x25, 0x0a, 0x47, 0x6d, 0x0c, 0xbf, 0x00, 0xa6, 0x93,
	0x0d, 0xd7, 0x52, 0x22, 0x31, 0xf6, 0xe4, 0xae, 0xcf, 0x41, 0x56, 0x05, 0xb9, 0x87, 0x4b, 0x82,
	0x63, 0x14, 0x86, 0x99, 0xb3, 0x41, 0x1a, 0x26, 0x66, 0x47, 0x11, 0x29, 0x9f, 0x3d, 0x84, 0x89,
	0x20, 0x23, 0x71, 0x4e, 0x98, 0x0b, 0x42, 0x53, 0x3e, 0xf3, 0x11, 0x4a, 0x61, 0x6a, 0xe2, 0xbc,
	0x30, 0x14, 0xe6, 0xa8, 0x7c, 0xaa, 0x1e, 0x54, 0x46, 0x22, 0x48, 0x71, 0x5d, 0x30, 0x48, 0x62,
	0x56, 0x6e, 0xb3, 0x61, 0x5e, 0x96, 0xb3, 0xb8, 0x31, 0x82, 0x15, 0x31, 0x5c, 0xc8, 0x17, 0x25,
	0xa5, 0xc2, 0x17, 0x0f, 0x52, 0xe5, 0x6d, 0x25, 0x39, 0x1d, 0xbb, 0xad, 0x22, 0xc5, 0x8b, 0xd8,
	0x86, 0xcb, 0x49, 0x6d, 0xf9, 0xbb, 0xb9, 0x42, 0x29, 0xc4, 0x53, 0x1e, 0xb7, 0x64, 0xc6, 0x64,
	0x0f, 0xc8, 0xad, 0xdf, 0x61, 0x35, 0xb3, 0x08, 0x70, 0x47, 0x70, 0x67, 0x16, 0x86, 0xfc, 0x09,
	0x57, 0xb0, 0x96, 0xd3, 0x18, 0xb8, 0x9b, 0xfd, 0x0c, 0xb1, 0x5b, 0x94, 0x6f, 0x75, 0xba, 0x5c,
	0x62, 0x6f, 0xb5, 0xbc, 0x79, 0xe4, 0xae, 0x56, 0x10, 0xc8, 0xa9, 0xea, 0x41, 0x4d, 0xd0, 0x49,
	0xab, 0x49, 0x6e, 0x64, 0x41, 0xd3, 0xa4, 0xbb, 0x09, 0x37, 0x05, 0xa5, 0xbc, 0xbc, 0x32, 0x6f,
	0x2c, 0xb6, 0x57, 0xe2, 0xc6, 0xe9, 0x6a, 0x93, 0xbb, 0x6a, 0x30, 0x9b, 0xea, 0x36, 0x7c, 0x2d,
	0xa8, 0x52, 0xbd, 0x27, 0x37, 0x9d, 0xc0, 0x8b, 0x64, 0xf1, 0xe1, 0xaa, 0x42, 0x64, 0xd9, 0xc5,
	0x36, 0x8a, 0x4a, 0x51, 0xb6, 0x51, 0xbc, 0x30, 0xf3, 0x37, 0x0a, 0x1b, 0x53, 0xb6, 0x51, 0xac,
	0x4c, 0xe5, 0x9e, 0x0a, 0x4c, 0x8b, 0x6d, 0x8a, 0x2b, 0x82, 0x45, 0xac, 0xd9, 0xcc, 0x5d, 0xe2,
	0x3d, 0x9b, 0xd8, 0x25, 0x59, 0xc1, 0x52, 0xcf, 0xc5, 0xc4, 0xe0, 0xbf, 0x88, 0xa3, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xdd, 0xd8, 0x51, 0x31, 0x88, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KubedgeClient is the client API for Kubedge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KubedgeClient interface {
	// Sends a message
	FiveGDemo(ctx context.Context, in *EnodeRequest, opts ...grpc.CallOption) (*EPCReply, error)
	DetectNW(ctx context.Context, in *UERequest, opts ...grpc.CallOption) (*EPCReply, error)
	// call flow messages
	MME_PDN_CONNECT(ctx context.Context, in *MME_PDN_CONNECT_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	MME_PDN_DISCONNECT(ctx context.Context, in *MME_PDN_DISCONNECT_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	MME_ATTACH(ctx context.Context, in *MME_ATTACH_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	MME_DETACH(ctx context.Context, in *MME_DETACH_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	MME_HO(ctx context.Context, in *MME_HO_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	MME_TAU(ctx context.Context, in *MME_TAU_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	MME_SERVICE_REQUEST(ctx context.Context, in *MME_SERVICE_REQUEST_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	SGW_SESSION_CREATION(ctx context.Context, in *SGW_SESSION_CREATION_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	SGW_SESSION_DELETION(ctx context.Context, in *SGW_SESSION_DELETION_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	SGW_BEARER_CREATION(ctx context.Context, in *SGW_BEARER_CREATION_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	SGW_BEARER_DELETION(ctx context.Context, in *SGW_BEARER_DELETION_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	SGW_BEARER_MODIFICATION(ctx context.Context, in *SGW_BEARER_MODIFICATION_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	SGW_DEDICATED_BEARER_ACTIVATE(ctx context.Context, in *SGW_DEDICATED_BEARER_ACTIVATE_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	SGW_DEDICATED_BEARER_DEACTIVATE(ctx context.Context, in *SGW_DEDICATED_BEARER_DEACTIVATE_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	ENB_RRC_CONN_SETUP(ctx context.Context, in *ENB_RRC_CONN_SETUP_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	ENB_S1_SIG_CONN_SETUP(ctx context.Context, in *ENB_S1_SIG_CONN_SETUP_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	ENB_INITIAL_CTXT_SETUP(ctx context.Context, in *ENB_INITIAL_CTXT_SETUP_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	ENB_UE_CTX_RELEASE(ctx context.Context, in *ENB_UE_CTX_RELEASE_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	ENB_X2HO_PREP_OUT(ctx context.Context, in *ENB_X2HO_PREP_OUT_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	ENB_X2HO_PREP_IN(ctx context.Context, in *ENB_X2HO_PREP_IN_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	ENB_X2HO_EXEC_OUT(ctx context.Context, in *ENB_X2HO_EXEC_OUT_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	ENB_X2HO_EXEC_IN(ctx context.Context, in *ENB_X2HO_EXEC_IN_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	ENB_ERAB_SETUP(ctx context.Context, in *ENB_ERAB_SETUP_MSG, opts ...grpc.CallOption) (*SIMReply, error)
	ENB_ERAB_RELEASE(ctx context.Context, in *ENB_ERAB_RELEASE_MSG, opts ...grpc.CallOption) (*SIMReply, error)
}

type kubedgeClient struct {
	cc *grpc.ClientConn
}

func NewKubedgeClient(cc *grpc.ClientConn) KubedgeClient {
	return &kubedgeClient{cc}
}

func (c *kubedgeClient) FiveGDemo(ctx context.Context, in *EnodeRequest, opts ...grpc.CallOption) (*EPCReply, error) {
	out := new(EPCReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/FiveGDemo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) DetectNW(ctx context.Context, in *UERequest, opts ...grpc.CallOption) (*EPCReply, error) {
	out := new(EPCReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/DetectNW", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) MME_PDN_CONNECT(ctx context.Context, in *MME_PDN_CONNECT_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/MME_PDN_CONNECT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) MME_PDN_DISCONNECT(ctx context.Context, in *MME_PDN_DISCONNECT_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/MME_PDN_DISCONNECT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) MME_ATTACH(ctx context.Context, in *MME_ATTACH_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/MME_ATTACH", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) MME_DETACH(ctx context.Context, in *MME_DETACH_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/MME_DETACH", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) MME_HO(ctx context.Context, in *MME_HO_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/MME_HO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) MME_TAU(ctx context.Context, in *MME_TAU_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/MME_TAU", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) MME_SERVICE_REQUEST(ctx context.Context, in *MME_SERVICE_REQUEST_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/MME_SERVICE_REQUEST", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) SGW_SESSION_CREATION(ctx context.Context, in *SGW_SESSION_CREATION_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/SGW_SESSION_CREATION", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) SGW_SESSION_DELETION(ctx context.Context, in *SGW_SESSION_DELETION_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/SGW_SESSION_DELETION", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) SGW_BEARER_CREATION(ctx context.Context, in *SGW_BEARER_CREATION_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/SGW_BEARER_CREATION", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) SGW_BEARER_DELETION(ctx context.Context, in *SGW_BEARER_DELETION_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/SGW_BEARER_DELETION", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) SGW_BEARER_MODIFICATION(ctx context.Context, in *SGW_BEARER_MODIFICATION_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/SGW_BEARER_MODIFICATION", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) SGW_DEDICATED_BEARER_ACTIVATE(ctx context.Context, in *SGW_DEDICATED_BEARER_ACTIVATE_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/SGW_DEDICATED_BEARER_ACTIVATE", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) SGW_DEDICATED_BEARER_DEACTIVATE(ctx context.Context, in *SGW_DEDICATED_BEARER_DEACTIVATE_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/SGW_DEDICATED_BEARER_DEACTIVATE", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) ENB_RRC_CONN_SETUP(ctx context.Context, in *ENB_RRC_CONN_SETUP_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/ENB_RRC_CONN_SETUP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) ENB_S1_SIG_CONN_SETUP(ctx context.Context, in *ENB_S1_SIG_CONN_SETUP_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/ENB_S1_SIG_CONN_SETUP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) ENB_INITIAL_CTXT_SETUP(ctx context.Context, in *ENB_INITIAL_CTXT_SETUP_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/ENB_INITIAL_CTXT_SETUP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) ENB_UE_CTX_RELEASE(ctx context.Context, in *ENB_UE_CTX_RELEASE_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/ENB_UE_CTX_RELEASE", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) ENB_X2HO_PREP_OUT(ctx context.Context, in *ENB_X2HO_PREP_OUT_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/ENB_X2HO_PREP_OUT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) ENB_X2HO_PREP_IN(ctx context.Context, in *ENB_X2HO_PREP_IN_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/ENB_X2HO_PREP_IN", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) ENB_X2HO_EXEC_OUT(ctx context.Context, in *ENB_X2HO_EXEC_OUT_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/ENB_X2HO_EXEC_OUT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) ENB_X2HO_EXEC_IN(ctx context.Context, in *ENB_X2HO_EXEC_IN_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/ENB_X2HO_EXEC_IN", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) ENB_ERAB_SETUP(ctx context.Context, in *ENB_ERAB_SETUP_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/ENB_ERAB_SETUP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubedgeClient) ENB_ERAB_RELEASE(ctx context.Context, in *ENB_ERAB_RELEASE_MSG, opts ...grpc.CallOption) (*SIMReply, error) {
	out := new(SIMReply)
	err := c.cc.Invoke(ctx, "/kubedge.Kubedge/ENB_ERAB_RELEASE", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KubedgeServer is the server API for Kubedge service.
type KubedgeServer interface {
	// Sends a message
	FiveGDemo(context.Context, *EnodeRequest) (*EPCReply, error)
	DetectNW(context.Context, *UERequest) (*EPCReply, error)
	// call flow messages
	MME_PDN_CONNECT(context.Context, *MME_PDN_CONNECT_MSG) (*SIMReply, error)
	MME_PDN_DISCONNECT(context.Context, *MME_PDN_DISCONNECT_MSG) (*SIMReply, error)
	MME_ATTACH(context.Context, *MME_ATTACH_MSG) (*SIMReply, error)
	MME_DETACH(context.Context, *MME_DETACH_MSG) (*SIMReply, error)
	MME_HO(context.Context, *MME_HO_MSG) (*SIMReply, error)
	MME_TAU(context.Context, *MME_TAU_MSG) (*SIMReply, error)
	MME_SERVICE_REQUEST(context.Context, *MME_SERVICE_REQUEST_MSG) (*SIMReply, error)
	SGW_SESSION_CREATION(context.Context, *SGW_SESSION_CREATION_MSG) (*SIMReply, error)
	SGW_SESSION_DELETION(context.Context, *SGW_SESSION_DELETION_MSG) (*SIMReply, error)
	SGW_BEARER_CREATION(context.Context, *SGW_BEARER_CREATION_MSG) (*SIMReply, error)
	SGW_BEARER_DELETION(context.Context, *SGW_BEARER_DELETION_MSG) (*SIMReply, error)
	SGW_BEARER_MODIFICATION(context.Context, *SGW_BEARER_MODIFICATION_MSG) (*SIMReply, error)
	SGW_DEDICATED_BEARER_ACTIVATE(context.Context, *SGW_DEDICATED_BEARER_ACTIVATE_MSG) (*SIMReply, error)
	SGW_DEDICATED_BEARER_DEACTIVATE(context.Context, *SGW_DEDICATED_BEARER_DEACTIVATE_MSG) (*SIMReply, error)
	ENB_RRC_CONN_SETUP(context.Context, *ENB_RRC_CONN_SETUP_MSG) (*SIMReply, error)
	ENB_S1_SIG_CONN_SETUP(context.Context, *ENB_S1_SIG_CONN_SETUP_MSG) (*SIMReply, error)
	ENB_INITIAL_CTXT_SETUP(context.Context, *ENB_INITIAL_CTXT_SETUP_MSG) (*SIMReply, error)
	ENB_UE_CTX_RELEASE(context.Context, *ENB_UE_CTX_RELEASE_MSG) (*SIMReply, error)
	ENB_X2HO_PREP_OUT(context.Context, *ENB_X2HO_PREP_OUT_MSG) (*SIMReply, error)
	ENB_X2HO_PREP_IN(context.Context, *ENB_X2HO_PREP_IN_MSG) (*SIMReply, error)
	ENB_X2HO_EXEC_OUT(context.Context, *ENB_X2HO_EXEC_OUT_MSG) (*SIMReply, error)
	ENB_X2HO_EXEC_IN(context.Context, *ENB_X2HO_EXEC_IN_MSG) (*SIMReply, error)
	ENB_ERAB_SETUP(context.Context, *ENB_ERAB_SETUP_MSG) (*SIMReply, error)
	ENB_ERAB_RELEASE(context.Context, *ENB_ERAB_RELEASE_MSG) (*SIMReply, error)
}

func RegisterKubedgeServer(s *grpc.Server, srv KubedgeServer) {
	s.RegisterService(&_Kubedge_serviceDesc, srv)
}

func _Kubedge_FiveGDemo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).FiveGDemo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/FiveGDemo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).FiveGDemo(ctx, req.(*EnodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_DetectNW_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UERequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).DetectNW(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/DetectNW",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).DetectNW(ctx, req.(*UERequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_MME_PDN_CONNECT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MME_PDN_CONNECT_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).MME_PDN_CONNECT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/MME_PDN_CONNECT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).MME_PDN_CONNECT(ctx, req.(*MME_PDN_CONNECT_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_MME_PDN_DISCONNECT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MME_PDN_DISCONNECT_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).MME_PDN_DISCONNECT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/MME_PDN_DISCONNECT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).MME_PDN_DISCONNECT(ctx, req.(*MME_PDN_DISCONNECT_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_MME_ATTACH_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MME_ATTACH_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).MME_ATTACH(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/MME_ATTACH",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).MME_ATTACH(ctx, req.(*MME_ATTACH_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_MME_DETACH_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MME_DETACH_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).MME_DETACH(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/MME_DETACH",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).MME_DETACH(ctx, req.(*MME_DETACH_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_MME_HO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MME_HO_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).MME_HO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/MME_HO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).MME_HO(ctx, req.(*MME_HO_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_MME_TAU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MME_TAU_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).MME_TAU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/MME_TAU",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).MME_TAU(ctx, req.(*MME_TAU_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_MME_SERVICE_REQUEST_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MME_SERVICE_REQUEST_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).MME_SERVICE_REQUEST(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/MME_SERVICE_REQUEST",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).MME_SERVICE_REQUEST(ctx, req.(*MME_SERVICE_REQUEST_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_SGW_SESSION_CREATION_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SGW_SESSION_CREATION_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).SGW_SESSION_CREATION(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/SGW_SESSION_CREATION",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).SGW_SESSION_CREATION(ctx, req.(*SGW_SESSION_CREATION_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_SGW_SESSION_DELETION_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SGW_SESSION_DELETION_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).SGW_SESSION_DELETION(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/SGW_SESSION_DELETION",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).SGW_SESSION_DELETION(ctx, req.(*SGW_SESSION_DELETION_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_SGW_BEARER_CREATION_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SGW_BEARER_CREATION_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).SGW_BEARER_CREATION(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/SGW_BEARER_CREATION",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).SGW_BEARER_CREATION(ctx, req.(*SGW_BEARER_CREATION_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_SGW_BEARER_DELETION_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SGW_BEARER_DELETION_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).SGW_BEARER_DELETION(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/SGW_BEARER_DELETION",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).SGW_BEARER_DELETION(ctx, req.(*SGW_BEARER_DELETION_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_SGW_BEARER_MODIFICATION_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SGW_BEARER_MODIFICATION_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).SGW_BEARER_MODIFICATION(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/SGW_BEARER_MODIFICATION",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).SGW_BEARER_MODIFICATION(ctx, req.(*SGW_BEARER_MODIFICATION_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_SGW_DEDICATED_BEARER_ACTIVATE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SGW_DEDICATED_BEARER_ACTIVATE_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).SGW_DEDICATED_BEARER_ACTIVATE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/SGW_DEDICATED_BEARER_ACTIVATE",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).SGW_DEDICATED_BEARER_ACTIVATE(ctx, req.(*SGW_DEDICATED_BEARER_ACTIVATE_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_SGW_DEDICATED_BEARER_DEACTIVATE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SGW_DEDICATED_BEARER_DEACTIVATE_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).SGW_DEDICATED_BEARER_DEACTIVATE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/SGW_DEDICATED_BEARER_DEACTIVATE",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).SGW_DEDICATED_BEARER_DEACTIVATE(ctx, req.(*SGW_DEDICATED_BEARER_DEACTIVATE_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_ENB_RRC_CONN_SETUP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ENB_RRC_CONN_SETUP_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).ENB_RRC_CONN_SETUP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/ENB_RRC_CONN_SETUP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).ENB_RRC_CONN_SETUP(ctx, req.(*ENB_RRC_CONN_SETUP_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_ENB_S1_SIG_CONN_SETUP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ENB_S1_SIG_CONN_SETUP_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).ENB_S1_SIG_CONN_SETUP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/ENB_S1_SIG_CONN_SETUP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).ENB_S1_SIG_CONN_SETUP(ctx, req.(*ENB_S1_SIG_CONN_SETUP_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_ENB_INITIAL_CTXT_SETUP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ENB_INITIAL_CTXT_SETUP_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).ENB_INITIAL_CTXT_SETUP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/ENB_INITIAL_CTXT_SETUP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).ENB_INITIAL_CTXT_SETUP(ctx, req.(*ENB_INITIAL_CTXT_SETUP_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_ENB_UE_CTX_RELEASE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ENB_UE_CTX_RELEASE_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).ENB_UE_CTX_RELEASE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/ENB_UE_CTX_RELEASE",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).ENB_UE_CTX_RELEASE(ctx, req.(*ENB_UE_CTX_RELEASE_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_ENB_X2HO_PREP_OUT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ENB_X2HO_PREP_OUT_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).ENB_X2HO_PREP_OUT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/ENB_X2HO_PREP_OUT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).ENB_X2HO_PREP_OUT(ctx, req.(*ENB_X2HO_PREP_OUT_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_ENB_X2HO_PREP_IN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ENB_X2HO_PREP_IN_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).ENB_X2HO_PREP_IN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/ENB_X2HO_PREP_IN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).ENB_X2HO_PREP_IN(ctx, req.(*ENB_X2HO_PREP_IN_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_ENB_X2HO_EXEC_OUT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ENB_X2HO_EXEC_OUT_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).ENB_X2HO_EXEC_OUT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/ENB_X2HO_EXEC_OUT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).ENB_X2HO_EXEC_OUT(ctx, req.(*ENB_X2HO_EXEC_OUT_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_ENB_X2HO_EXEC_IN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ENB_X2HO_EXEC_IN_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).ENB_X2HO_EXEC_IN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/ENB_X2HO_EXEC_IN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).ENB_X2HO_EXEC_IN(ctx, req.(*ENB_X2HO_EXEC_IN_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_ENB_ERAB_SETUP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ENB_ERAB_SETUP_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).ENB_ERAB_SETUP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/ENB_ERAB_SETUP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).ENB_ERAB_SETUP(ctx, req.(*ENB_ERAB_SETUP_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kubedge_ENB_ERAB_RELEASE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ENB_ERAB_RELEASE_MSG)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubedgeServer).ENB_ERAB_RELEASE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubedge.Kubedge/ENB_ERAB_RELEASE",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubedgeServer).ENB_ERAB_RELEASE(ctx, req.(*ENB_ERAB_RELEASE_MSG))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kubedge_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubedge.Kubedge",
	HandlerType: (*KubedgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FiveGDemo",
			Handler:    _Kubedge_FiveGDemo_Handler,
		},
		{
			MethodName: "DetectNW",
			Handler:    _Kubedge_DetectNW_Handler,
		},
		{
			MethodName: "MME_PDN_CONNECT",
			Handler:    _Kubedge_MME_PDN_CONNECT_Handler,
		},
		{
			MethodName: "MME_PDN_DISCONNECT",
			Handler:    _Kubedge_MME_PDN_DISCONNECT_Handler,
		},
		{
			MethodName: "MME_ATTACH",
			Handler:    _Kubedge_MME_ATTACH_Handler,
		},
		{
			MethodName: "MME_DETACH",
			Handler:    _Kubedge_MME_DETACH_Handler,
		},
		{
			MethodName: "MME_HO",
			Handler:    _Kubedge_MME_HO_Handler,
		},
		{
			MethodName: "MME_TAU",
			Handler:    _Kubedge_MME_TAU_Handler,
		},
		{
			MethodName: "MME_SERVICE_REQUEST",
			Handler:    _Kubedge_MME_SERVICE_REQUEST_Handler,
		},
		{
			MethodName: "SGW_SESSION_CREATION",
			Handler:    _Kubedge_SGW_SESSION_CREATION_Handler,
		},
		{
			MethodName: "SGW_SESSION_DELETION",
			Handler:    _Kubedge_SGW_SESSION_DELETION_Handler,
		},
		{
			MethodName: "SGW_BEARER_CREATION",
			Handler:    _Kubedge_SGW_BEARER_CREATION_Handler,
		},
		{
			MethodName: "SGW_BEARER_DELETION",
			Handler:    _Kubedge_SGW_BEARER_DELETION_Handler,
		},
		{
			MethodName: "SGW_BEARER_MODIFICATION",
			Handler:    _Kubedge_SGW_BEARER_MODIFICATION_Handler,
		},
		{
			MethodName: "SGW_DEDICATED_BEARER_ACTIVATE",
			Handler:    _Kubedge_SGW_DEDICATED_BEARER_ACTIVATE_Handler,
		},
		{
			MethodName: "SGW_DEDICATED_BEARER_DEACTIVATE",
			Handler:    _Kubedge_SGW_DEDICATED_BEARER_DEACTIVATE_Handler,
		},
		{
			MethodName: "ENB_RRC_CONN_SETUP",
			Handler:    _Kubedge_ENB_RRC_CONN_SETUP_Handler,
		},
		{
			MethodName: "ENB_S1_SIG_CONN_SETUP",
			Handler:    _Kubedge_ENB_S1_SIG_CONN_SETUP_Handler,
		},
		{
			MethodName: "ENB_INITIAL_CTXT_SETUP",
			Handler:    _Kubedge_ENB_INITIAL_CTXT_SETUP_Handler,
		},
		{
			MethodName: "ENB_UE_CTX_RELEASE",
			Handler:    _Kubedge_ENB_UE_CTX_RELEASE_Handler,
		},
		{
			MethodName: "ENB_X2HO_PREP_OUT",
			Handler:    _Kubedge_ENB_X2HO_PREP_OUT_Handler,
		},
		{
			MethodName: "ENB_X2HO_PREP_IN",
			Handler:    _Kubedge_ENB_X2HO_PREP_IN_Handler,
		},
		{
			MethodName: "ENB_X2HO_EXEC_OUT",
			Handler:    _Kubedge_ENB_X2HO_EXEC_OUT_Handler,
		},
		{
			MethodName: "ENB_X2HO_EXEC_IN",
			Handler:    _Kubedge_ENB_X2HO_EXEC_IN_Handler,
		},
		{
			MethodName: "ENB_ERAB_SETUP",
			Handler:    _Kubedge_ENB_ERAB_SETUP_Handler,
		},
		{
			MethodName: "ENB_ERAB_RELEASE",
			Handler:    _Kubedge_ENB_ERAB_RELEASE_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kubedge.proto",
}
