sudo: true

language: go

go:
  - "1.11.x"

service:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - export DHUBREPO=$DOCKER_NAMESPACE/kubesim_base-amd64
      - export VERSION=0.1.0
      - cd kubesim_base
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o goserv .
      - cd ..
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - stage: test
      script:
      - export DHUBREPO=$DOCKER_NAMESPACE/kubesim_base-amd64
      - export VERSION=0.1.0
