sudo: true

language: go

go:
  - "1.10.x"

service:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - export DHUBREPO=$DOCKER_NAMESPACE/kubesim_base-arm32v7
      - export VERSION=0.1.0
      - cd kubesim_base
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o goserv .
      - cd ..
      - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - stage: test
      script:
      - export DHUBREPO=$DOCKER_NAMESPACE/kubesim_base-arm32v7
      - export VERSION=0.1.0
