# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import kubedge_pb2 as kubedge__pb2


class KubedgeStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.FiveGDemo = channel.unary_unary(
        '/kubedge.Kubedge/FiveGDemo',
        request_serializer=kubedge__pb2.EnodeRequest.SerializeToString,
        response_deserializer=kubedge__pb2.EPCReply.FromString,
        )
    self.DetectNW = channel.unary_unary(
        '/kubedge.Kubedge/DetectNW',
        request_serializer=kubedge__pb2.UERequest.SerializeToString,
        response_deserializer=kubedge__pb2.EPCReply.FromString,
        )


class KubedgeServicer(object):
  """The greeting service definition.
  """

  def FiveGDemo(self, request, context):
    """Sends a message
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DetectNW(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KubedgeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'FiveGDemo': grpc.unary_unary_rpc_method_handler(
          servicer.FiveGDemo,
          request_deserializer=kubedge__pb2.EnodeRequest.FromString,
          response_serializer=kubedge__pb2.EPCReply.SerializeToString,
      ),
      'DetectNW': grpc.unary_unary_rpc_method_handler(
          servicer.DetectNW,
          request_deserializer=kubedge__pb2.UERequest.FromString,
          response_serializer=kubedge__pb2.EPCReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'kubedge.Kubedge', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
